### ISSUE TITLE
Is bitcoinj-core dependency unnecessary?

### ISSUE THREAD

**Issue by ftong2010** [jleskovar/btc-rpc-client#1]
So glad that I find this project, it fits my need so well, 👍 

I am just curious about the dependency bitjoinj-core in pom.xml. No where I can find a import or reference to it, is there any special reason you keep it as a dependency?

**Comment by jleskovar-tyro** [comment]
Hey there,

Probably not - it’s most likely a vestige of when this was originally going to be a Kotlin wrapper for bitcoinj. I will remove it next release

**Comment by jleskovar** [comment]
Removed from master
